package co.in.pp;
// Generated May 31, 2018 7:25:50 PM by Hibernate Tools 3.5.0.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Bugstatus generated by hbm2java
 */
@Entity
@Table(name = "bugstatus", catalog = "hibernate_project_annotation")
public class Bugstatus implements java.io.Serializable {

	private Integer SId;
	private Employee employee;
	private String bugName;
	private String status;
	private Date submissionDate;
	private Bugs bugs;

	public Bugstatus() {
	}

	public Bugstatus(Employee employee, String bugName, String status, Date submissionDate, Bugs bugs) {
		this.employee = employee;
		this.bugName = bugName;
		this.status = status;
		this.submissionDate = submissionDate;
		this.bugs = bugs;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "S_ID", unique = true, nullable = false)
	public Integer getSId() {
		return this.SId;
	}

	public void setSId(Integer SId) {
		this.SId = SId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "E_ID")
	public Employee getEmployee() {
		return this.employee;
	}

	public void setEmployee(Employee employee) {
		this.employee = employee;
	}

	@Column(name = "BUG_NAME")
	public String getBugName() {
		return this.bugName;
	}

	public void setBugName(String bugName) {
		this.bugName = bugName;
	}

	@Column(name = "STATUS")
	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "SUBMISSION_DATE", length = 19)
	public Date getSubmissionDate() {
		return this.submissionDate;
	}

	public void setSubmissionDate(Date submissionDate) {
		this.submissionDate = submissionDate;
	}

	@OneToOne(fetch = FetchType.LAZY, mappedBy = "bugstatus")
	public Bugs getBugs() {
		return this.bugs;
	}

	public void setBugs(Bugs bugs) {
		this.bugs = bugs;
	}

}
