package co.in.pp;
// Generated May 31, 2018 7:25:50 PM by Hibernate Tools 3.5.0.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.OneToOne;
import javax.persistence.PrimaryKeyJoinColumn;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import org.hibernate.annotations.GenericGenerator;
import org.hibernate.annotations.Parameter;

/**
 * Bugs generated by hbm2java
 */
@Entity
@Table(name = "bugs", catalog = "hibernate_project_annotation")
public class Bugs implements java.io.Serializable {

	private Integer bugId;
	private Project project;
	private Bugstatus bugstatus;
	private String bugDescription;
	private Date bugEndDate;
	private String bugName;
	private Date bugStartDate;
	private Set<Chatbug> chatbugs = new HashSet<Chatbug>(0);

	public Bugs() {
	}

	public Bugs(Bugstatus bugstatus) {
		this.bugstatus = bugstatus;
	}

	public Bugs(Project project, Bugstatus bugstatus, String bugDescription, Date bugEndDate, String bugName,
			Date bugStartDate, Set<Chatbug> chatbugs) {
		this.project = project;
		this.bugstatus = bugstatus;
		this.bugDescription = bugDescription;
		this.bugEndDate = bugEndDate;
		this.bugName = bugName;
		this.bugStartDate = bugStartDate;
		this.chatbugs = chatbugs;
	}

	@GenericGenerator(name = "generator", strategy = "foreign", parameters = @Parameter(name = "property", value = "bugstatus"))
	@Id
	@GeneratedValue(generator = "generator")

	@Column(name = "BUG_ID", unique = true, nullable = false)
	public Integer getBugId() {
		return this.bugId;
	}

	public void setBugId(Integer bugId) {
		this.bugId = bugId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "PROJECT_ID")
	public Project getProject() {
		return this.project;
	}

	public void setProject(Project project) {
		this.project = project;
	}

	@OneToOne(fetch = FetchType.LAZY)
	@PrimaryKeyJoinColumn
	public Bugstatus getBugstatus() {
		return this.bugstatus;
	}

	public void setBugstatus(Bugstatus bugstatus) {
		this.bugstatus = bugstatus;
	}

	@Column(name = "BUG_DESCRIPTION")
	public String getBugDescription() {
		return this.bugDescription;
	}

	public void setBugDescription(String bugDescription) {
		this.bugDescription = bugDescription;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "BUG_END_DATE", length = 10)
	public Date getBugEndDate() {
		return this.bugEndDate;
	}

	public void setBugEndDate(Date bugEndDate) {
		this.bugEndDate = bugEndDate;
	}

	@Column(name = "BUG_NAME")
	public String getBugName() {
		return this.bugName;
	}

	public void setBugName(String bugName) {
		this.bugName = bugName;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "BUG_START_DATE", length = 10)
	public Date getBugStartDate() {
		return this.bugStartDate;
	}

	public void setBugStartDate(Date bugStartDate) {
		this.bugStartDate = bugStartDate;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "bugs")
	public Set<Chatbug> getChatbugs() {
		return this.chatbugs;
	}

	public void setChatbugs(Set<Chatbug> chatbugs) {
		this.chatbugs = chatbugs;
	}

}
