package co.in.pp;
// Generated May 31, 2018 7:25:50 PM by Hibernate Tools 3.5.0.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Employee generated by hbm2java
 */
@Entity
@Table(name = "employee", catalog = "hibernate_project_annotation")
public class Employee implements java.io.Serializable {

	private Integer EId;
	private Team team;
	private Date dateOfBirth;
	private String email;
	private String firstName;
	private String lastName;
	private Integer mobile;
	private String role;
	private Set<Chatbug> chatbugs = new HashSet<Chatbug>(0);
	private Set<Bugstatus> bugstatuses = new HashSet<Bugstatus>(0);
	private Set<Empmilestone> empmilestones = new HashSet<Empmilestone>(0);

	public Employee() {
	}

	public Employee(Team team, Date dateOfBirth, String email, String firstName, String lastName, Integer mobile,
			String role, Set<Chatbug> chatbugs, Set<Bugstatus> bugstatuses, Set<Empmilestone> empmilestones) {
		this.team = team;
		this.dateOfBirth = dateOfBirth;
		this.email = email;
		this.firstName = firstName;
		this.lastName = lastName;
		this.mobile = mobile;
		this.role = role;
		this.chatbugs = chatbugs;
		this.bugstatuses = bugstatuses;
		this.empmilestones = empmilestones;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "E_ID", unique = true, nullable = false)
	public Integer getEId() {
		return this.EId;
	}

	public void setEId(Integer EId) {
		this.EId = EId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "T_ID")
	public Team getTeam() {
		return this.team;
	}

	public void setTeam(Team team) {
		this.team = team;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "DATE_OF_BIRTH", length = 10)
	public Date getDateOfBirth() {
		return this.dateOfBirth;
	}

	public void setDateOfBirth(Date dateOfBirth) {
		this.dateOfBirth = dateOfBirth;
	}

	@Column(name = "EMAIL")
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	@Column(name = "FIRST_NAME")
	public String getFirstName() {
		return this.firstName;
	}

	public void setFirstName(String firstName) {
		this.firstName = firstName;
	}

	@Column(name = "LAST_NAME")
	public String getLastName() {
		return this.lastName;
	}

	public void setLastName(String lastName) {
		this.lastName = lastName;
	}

	@Column(name = "MOBILE")
	public Integer getMobile() {
		return this.mobile;
	}

	public void setMobile(Integer mobile) {
		this.mobile = mobile;
	}

	@Column(name = "ROLE")
	public String getRole() {
		return this.role;
	}

	public void setRole(String role) {
		this.role = role;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "employee")
	public Set<Chatbug> getChatbugs() {
		return this.chatbugs;
	}

	public void setChatbugs(Set<Chatbug> chatbugs) {
		this.chatbugs = chatbugs;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "employee")
	public Set<Bugstatus> getBugstatuses() {
		return this.bugstatuses;
	}

	public void setBugstatuses(Set<Bugstatus> bugstatuses) {
		this.bugstatuses = bugstatuses;
	}

	@ManyToMany(fetch = FetchType.LAZY)
	@JoinTable(name = "employeemilestone", catalog = "hibernate_project_annotation", joinColumns = {
			@JoinColumn(name = "EMP_ID", nullable = false, updatable = false) }, inverseJoinColumns = {
					@JoinColumn(name = "MILE_ID", nullable = false, updatable = false) })
	public Set<Empmilestone> getEmpmilestones() {
		return this.empmilestones;
	}

	public void setEmpmilestones(Set<Empmilestone> empmilestones) {
		this.empmilestones = empmilestones;
	}

}
