package co.in.pp;
// Generated May 31, 2018 7:25:50 PM by Hibernate Tools 3.5.0.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Empmilestone generated by hbm2java
 */
@Entity
@Table(name = "empmilestone", catalog = "hibernate_project_annotation")
public class Empmilestone implements java.io.Serializable {

	private Integer EMId;
	private Date EMDateDate;
	private String EMName;
	private Date EMStartDate;
	private Set<Employee> employees = new HashSet<Employee>(0);

	public Empmilestone() {
	}

	public Empmilestone(Date EMDateDate, String EMName, Date EMStartDate, Set<Employee> employees) {
		this.EMDateDate = EMDateDate;
		this.EMName = EMName;
		this.EMStartDate = EMStartDate;
		this.employees = employees;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "E_M_ID", unique = true, nullable = false)
	public Integer getEMId() {
		return this.EMId;
	}

	public void setEMId(Integer EMId) {
		this.EMId = EMId;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "E_M_DATE_DATE", length = 10)
	public Date getEMDateDate() {
		return this.EMDateDate;
	}

	public void setEMDateDate(Date EMDateDate) {
		this.EMDateDate = EMDateDate;
	}

	@Column(name = "E_M_NAME")
	public String getEMName() {
		return this.EMName;
	}

	public void setEMName(String EMName) {
		this.EMName = EMName;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "E_M_START_DATE", length = 10)
	public Date getEMStartDate() {
		return this.EMStartDate;
	}

	public void setEMStartDate(Date EMStartDate) {
		this.EMStartDate = EMStartDate;
	}

	@ManyToMany(fetch = FetchType.LAZY)
	@JoinTable(name = "employeemilestone", catalog = "hibernate_project_annotation", joinColumns = {
			@JoinColumn(name = "MILE_ID", nullable = false, updatable = false) }, inverseJoinColumns = {
					@JoinColumn(name = "EMP_ID", nullable = false, updatable = false) })
	public Set<Employee> getEmployees() {
		return this.employees;
	}

	public void setEmployees(Set<Employee> employees) {
		this.employees = employees;
	}

}
