package co.in.pp;
// Generated May 31, 2018 7:25:50 PM by Hibernate Tools 3.5.0.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToOne;
import javax.persistence.PrimaryKeyJoinColumn;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import org.hibernate.annotations.GenericGenerator;
import org.hibernate.annotations.Parameter;

/**
 * Login generated by hbm2java
 */
@Entity
@Table(name = "login", catalog = "hibernate_project_annotation")
public class Login implements java.io.Serializable {

	private Integer LId;
	private Customer customer;
	private Date accountCreationDate;
	private String alternatePassword;
	private String loginEmail;
	private String password;

	public Login() {
	}

	public Login(Customer customer) {
		this.customer = customer;
	}

	public Login(Customer customer, Date accountCreationDate, String alternatePassword, String loginEmail,
			String password) {
		this.customer = customer;
		this.accountCreationDate = accountCreationDate;
		this.alternatePassword = alternatePassword;
		this.loginEmail = loginEmail;
		this.password = password;
	}

	@GenericGenerator(name = "generator", strategy = "foreign", parameters = @Parameter(name = "property", value = "customer"))
	@Id
	@GeneratedValue(generator = "generator")

	@Column(name = "L_ID", unique = true, nullable = false)
	public Integer getLId() {
		return this.LId;
	}

	public void setLId(Integer LId) {
		this.LId = LId;
	}

	@OneToOne(fetch = FetchType.LAZY)
	@PrimaryKeyJoinColumn
	public Customer getCustomer() {
		return this.customer;
	}

	public void setCustomer(Customer customer) {
		this.customer = customer;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "ACCOUNT_CREATION_DATE", length = 10)
	public Date getAccountCreationDate() {
		return this.accountCreationDate;
	}

	public void setAccountCreationDate(Date accountCreationDate) {
		this.accountCreationDate = accountCreationDate;
	}

	@Column(name = "ALTERNATE_PASSWORD")
	public String getAlternatePassword() {
		return this.alternatePassword;
	}

	public void setAlternatePassword(String alternatePassword) {
		this.alternatePassword = alternatePassword;
	}

	@Column(name = "LOGIN_EMAIL")
	public String getLoginEmail() {
		return this.loginEmail;
	}

	public void setLoginEmail(String loginEmail) {
		this.loginEmail = loginEmail;
	}

	@Column(name = "PASSWORD")
	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

}
