package co.in.pp;
// Generated May 31, 2018 7:25:50 PM by Hibernate Tools 3.5.0.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.OneToOne;
import javax.persistence.PrimaryKeyJoinColumn;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import org.hibernate.annotations.GenericGenerator;
import org.hibernate.annotations.Parameter;

/**
 * Project generated by hbm2java
 */
@Entity
@Table(name = "project", catalog = "hibernate_project_annotation")
public class Project implements java.io.Serializable {

	private Integer PId;
	private Projectstatus projectstatus;
	private Customer customer;
	private Projectgroup projectgroup;
	private String description;
	private Date endDate;
	private String PName;
	private Date startDate;
	private Set<Bugs> bugses = new HashSet<Bugs>(0);
	private Set<Projectmilestone> projectmilestones = new HashSet<Projectmilestone>(0);

	public Project() {
	}

	public Project(Projectstatus projectstatus) {
		this.projectstatus = projectstatus;
	}

	public Project(Projectstatus projectstatus, Customer customer, Projectgroup projectgroup, String description,
			Date endDate, String PName, Date startDate, Set<Bugs> bugses, Set<Projectmilestone> projectmilestones) {
		this.projectstatus = projectstatus;
		this.customer = customer;
		this.projectgroup = projectgroup;
		this.description = description;
		this.endDate = endDate;
		this.PName = PName;
		this.startDate = startDate;
		this.bugses = bugses;
		this.projectmilestones = projectmilestones;
	}

	@GenericGenerator(name = "generator", strategy = "foreign", parameters = @Parameter(name = "property", value = "projectstatus"))
	@Id
	@GeneratedValue(generator = "generator")

	@Column(name = "P_ID", unique = true, nullable = false)
	public Integer getPId() {
		return this.PId;
	}

	public void setPId(Integer PId) {
		this.PId = PId;
	}

	@OneToOne(fetch = FetchType.LAZY)
	@PrimaryKeyJoinColumn
	public Projectstatus getProjectstatus() {
		return this.projectstatus;
	}

	public void setProjectstatus(Projectstatus projectstatus) {
		this.projectstatus = projectstatus;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CUS_ID")
	public Customer getCustomer() {
		return this.customer;
	}

	public void setCustomer(Customer customer) {
		this.customer = customer;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "PG_ID")
	public Projectgroup getProjectgroup() {
		return this.projectgroup;
	}

	public void setProjectgroup(Projectgroup projectgroup) {
		this.projectgroup = projectgroup;
	}

	@Column(name = "DESCRIPTION")
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "END_DATE", length = 10)
	public Date getEndDate() {
		return this.endDate;
	}

	public void setEndDate(Date endDate) {
		this.endDate = endDate;
	}

	@Column(name = "P_NAME")
	public String getPName() {
		return this.PName;
	}

	public void setPName(String PName) {
		this.PName = PName;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "START_DATE", length = 10)
	public Date getStartDate() {
		return this.startDate;
	}

	public void setStartDate(Date startDate) {
		this.startDate = startDate;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "project")
	public Set<Bugs> getBugses() {
		return this.bugses;
	}

	public void setBugses(Set<Bugs> bugses) {
		this.bugses = bugses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "project")
	public Set<Projectmilestone> getProjectmilestones() {
		return this.projectmilestones;
	}

	public void setProjectmilestones(Set<Projectmilestone> projectmilestones) {
		this.projectmilestones = projectmilestones;
	}

}
