package co.in.pp;
// Generated May 31, 2018 7:25:50 PM by Hibernate Tools 3.5.0.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Projectstatus generated by hbm2java
 */
@Entity
@Table(name = "projectstatus", catalog = "hibernate_project_annotation")
public class Projectstatus implements java.io.Serializable {

	private Integer SId;
	private Team team;
	private String projectName;
	private String status;
	private Date submissionDate;
	private Project project;

	public Projectstatus() {
	}

	public Projectstatus(Team team, String projectName, String status, Date submissionDate, Project project) {
		this.team = team;
		this.projectName = projectName;
		this.status = status;
		this.submissionDate = submissionDate;
		this.project = project;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "S_ID", unique = true, nullable = false)
	public Integer getSId() {
		return this.SId;
	}

	public void setSId(Integer SId) {
		this.SId = SId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "T_ID")
	public Team getTeam() {
		return this.team;
	}

	public void setTeam(Team team) {
		this.team = team;
	}

	@Column(name = "PROJECT_NAME")
	public String getProjectName() {
		return this.projectName;
	}

	public void setProjectName(String projectName) {
		this.projectName = projectName;
	}

	@Column(name = "STATUS")
	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "SUBMISSION_DATE", length = 10)
	public Date getSubmissionDate() {
		return this.submissionDate;
	}

	public void setSubmissionDate(Date submissionDate) {
		this.submissionDate = submissionDate;
	}

	@OneToOne(fetch = FetchType.LAZY, mappedBy = "projectstatus")
	public Project getProject() {
		return this.project;
	}

	public void setProject(Project project) {
		this.project = project;
	}

}
